name: Jakarta EE 10 CI

on:
  push:
    branches:
      - main  # oder Ihre Hauptbranch-Namen
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout des Codes
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install  # Oder mvn clean package für WAR-Archiv
      - name: Run Tests
        run: mvn test
      # Optional: Hier können Sie weitere Schritte wie Codeanalyse (SonarQube), etc. hinzufügen
      - name: Upload Artifacts (optional, z.B. für WAR-Datei)
        uses: actions/upload-artifact@v4
        with:
          name: application-artifact
          path: target/*.war  # Pfad zur WAR-Datei